using Godot;

public partial class GameFlowUI
{
	private const string PlayerPath = "../../Player";
	private const string StartPanelPath = "Panels/StartPanel";
	private const string StartMainVBoxPath = "Panels/StartPanel/Panel/MainScroll/VBox";
	private const string StartSettingsPanelPath = "Panels/StartPanel/Panel/SettingsPanel";
	private const string StartCardsPanelPath = "Panels/StartPanel/Panel/CardsPanel";
	private const string StartCharacterSelectPanelPath = "Panels/StartPanel/Panel/CharacterSelectPanel";
	private const string StartCharacterRangedButtonPath = "Panels/StartPanel/Panel/CharacterSelectPanel/VBox/ContentRow/LeftColumn/CharacterButtons/RangedButton";
	private const string StartCharacterSwordsmanButtonPath = "Panels/StartPanel/Panel/CharacterSelectPanel/VBox/ContentRow/LeftColumn/CharacterButtons/SwordsmanButton";
	private const string StartCharacterTankButtonPath = "Panels/StartPanel/Panel/CharacterSelectPanel/VBox/ContentRow/LeftColumn/CharacterButtons/TankButton";
	private const string StartCharacterArcherButtonPath = "Panels/StartPanel/Panel/CharacterSelectPanel/VBox/ContentRow/LeftColumn/CharacterButtons/ArcherButton";
	private const string StartCharacterDescriptionPath = "Panels/StartPanel/Panel/CharacterSelectPanel/VBox/BottomRow/DetailPanel/Margin/DescScroll/SelectedCharacterDesc";
	private const string StartCharacterFluxValuePath = "Panels/StartPanel/Panel/CharacterSelectPanel/VBox/HeaderRow/FluxHeader/FluxValue";
	private const string StartCharacterBackButtonPath = "Panels/StartPanel/Panel/CharacterSelectPanel/VBox/ActionButtons/BackButton";
	private const string StartCharacterConfirmButtonPath = "Panels/StartPanel/Panel/CharacterSelectPanel/VBox/ActionButtons/ConfirmButton";
	private const string RestartPanelPath = "Panels/RestartPanel";
	private const string PausePanelPath = "Panels/PausePanel";
	private const string PauseMainVBoxPath = "Panels/PausePanel/Panel/VBox";
	private const string PauseSettingsPanelPath = "Panels/PausePanel/Panel/SettingsPanel";
	private const string StartButtonPath = "Panels/StartPanel/Panel/MainScroll/VBox/MainBody/RightColumnPanel/Margin/ButtonsVBox/StartButton";
	private const string StartSettingsButtonPath = "Panels/StartPanel/Panel/MainScroll/VBox/MainBody/RightColumnPanel/Margin/ButtonsVBox/SettingsButton";
	private const string StartCardsButtonPath = "Panels/StartPanel/Panel/MainScroll/VBox/MainBody/RightColumnPanel/Margin/ButtonsVBox/CardsButton";
	private const string StartQuitButtonPath = "Panels/StartPanel/Panel/MainScroll/VBox/MainBody/RightColumnPanel/Margin/ButtonsVBox/QuitButton";
	private const string StartDeleteSaveButtonPath = "Panels/StartPanel/Panel/SettingsPanel/SettingsScroll/VBox/DeleteSaveButton";
	private const string StartDeleteSaveDialogPath = "Panels/StartPanel/DeleteSaveConfirmDialog";
	private const string StartPerfectLeaderboardPath = "Panels/StartPanel/Panel/MainScroll/VBox/MainBody/LeftColumn/PerfectLeaderboard";
	private const string StartSettingsBackButtonPath = "Panels/StartPanel/Panel/SettingsPanel/SettingsScroll/VBox/BackButton";
	private const string StartCardsBackButtonPath = "Panels/StartPanel/Panel/CardsPanel/VBox/BackButton";
	private const string StartCardsContentPath = "Panels/StartPanel/Panel/CardsPanel/VBox/CardsScroll/CardsContent";
	private const string StartSettingsBgmSliderPath = "Panels/StartPanel/Panel/SettingsPanel/SettingsScroll/VBox/BgmSlider";
	private const string StartSettingsSfxSliderPath = "Panels/StartPanel/Panel/SettingsPanel/SettingsScroll/VBox/SfxSlider";
	private const string StartSettingsWindowSizePath = "Panels/StartPanel/Panel/SettingsPanel/SettingsScroll/VBox/WindowSizeOption";
	private const string StartSettingsWindowModePath = "Panels/StartPanel/Panel/SettingsPanel/SettingsScroll/VBox/WindowModeOption";
	private const string StartSettingsLanguagePath = "Panels/StartPanel/Panel/SettingsPanel/SettingsScroll/VBox/LanguageOption";
	private const string RestartBackToMetaButtonPath = "Panels/RestartPanel/Panel/Margin/VBox/ActionButtons/BackToMetaButton";
	private const string RestartButtonPath = "Panels/RestartPanel/Panel/Margin/VBox/ActionButtons/RestartButton";
	private const string PauseResumeButtonPath = "Panels/PausePanel/Panel/VBox/ResumeButton";
	private const string PauseSettingsButtonPath = "Panels/PausePanel/Panel/VBox/SettingsButton";
	private const string PauseRestartButtonPath = "Panels/PausePanel/Panel/VBox/RestartButton";
	private const string PauseToTitleButtonPath = "Panels/PausePanel/Panel/VBox/ToTitleButton";
	private const string PauseQuitButtonPath = "Panels/PausePanel/Panel/VBox/QuitButton";
	private const string SettingsBackButtonPath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/BackButton";
	private const string SettingsBgmSliderPath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/BgmSlider";
	private const string SettingsSfxSliderPath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/SfxSlider";
	private const string SettingsWindowSizePath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/WindowSizeOption";
	private const string SettingsWindowModePath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/WindowModeOption";
	private const string SettingsLanguagePath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/LanguageOption";
	private const string UpgradeMenuPath = "UpgradeLayer/UpgradeMenu";
	private const string ScoreLabelPath = "Overlay/HudOverlay/ScoreLabel";
	private const string PlayerHealthBarPath = "Overlay/HudOverlay/PlayerHealthBarDemo";
	private const string ExperienceBarRootPath = "Overlay/HudOverlay/ExperienceBarRoot";
	private const string ExperienceBarPath = "Overlay/HudOverlay/ExperienceBarRoot/ExperienceBar";
	private const string ExperienceLabelPath = "Overlay/HudOverlay/ExperienceBarRoot/ExperienceLabel";
	private const string MatchCountdownLabelPath = "Overlay/HudOverlay/MatchCountdownLabel";
	private const string FinalScoreLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/StatsPanel/StatsMargin/StatsRow/Score";
	private const string FinalSurvivalLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/StatsPanel/StatsMargin/StatsRow/Survival";
	private const string FinalFluxGainLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/StatsPanel/StatsMargin/StatsRow/FluxGain";
	private const string FinalFluxWalletLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/StatsPanel/StatsMargin/StatsRow/FluxWallet";
	private const string PauseBuildSummaryLabelPath = "Panels/PausePanel/Panel/VBox/BuildSummary";
	private const string FinalBuildSummaryLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/BuildSection/BuildMargin/BuildVBox/BuildScroll/BuildSummary";
	private const string RestartTitleLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/Header/Title";
	private const string RestartPerfectBannerPath = "Panels/RestartPanel/Panel/Margin/VBox/Header/PerfectBanner";
	private const string RestartHintLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/Header/Hint";
	private const string BackgroundPath = "../../World/Background";
	private const string BackgroundDimmerPath = "../../World/BackgroundDimmer";
	private const string MenuBackgroundPath = "../../World/MenuBackground";
	private const string MenuDimmerPath = "../../World/MenuDimmer";
	private const string EnemiesPath = "../../Enemies";
	private const string ProjectilesPath = "../../Projectiles";
	private const string ObstaclesPath = "../../World/Obstacles";
	private const string RangedCharacterResourcePath = "res://Data/Characters/RangedCharacter.tres";
	private const string SwordsmanCharacterResourcePath = "res://Data/Characters/SwordsmanCharacter.tres";
	private const string TankCharacterResourcePath = "res://Data/Characters/TankBurstCharacter.tres";
	private const string ArcherCharacterResourcePath = "res://Data/Characters/ArcherCharacter.tres";

	private Player _player;
	private PlayerHealth _playerHealth;
	private Control _startPanel;
	private Control _startMainVBox;
	private Control _startSettingsPanel;
	private Control _startCardsPanel;
	private Control _startCharacterSelectPanel;
	private Control _restartPanel;
	private Control _pausePanel;
	private Control _pauseMainVBox;
	private Control _pauseSettingsPanel;
	private Button _startButton;
	private Button _startSettingsButton;
	private Button _startCardsButton;
	private Button _startQuitButton;
	private Button _startDeleteSaveButton;
	private ConfirmationDialog _startDeleteSaveDialog;
	private Label _startPerfectLeaderboardLabel;
	private Button _startSettingsBackButton;
	private Button _startCardsBackButton;
	private Label _startCardsContentLabel;
	private Button _startCharacterRangedButton;
	private Button _startCharacterSwordsmanButton;
	private Button _startCharacterTankButton;
	private Button _startCharacterArcherButton;
	private Label _startCharacterFluxValueLabel;
	private Button _startCharacterBackButton;
	private Button _startCharacterConfirmButton;
	private Button _restartBackToMetaButton;
	private Button _restartButton;
	private Button _pauseResumeButton;
	private Button _pauseSettingsButton;
	private Button _pauseRestartButton;
	private Button _pauseToTitleButton;
	private Button _pauseQuitButton;
	private Button _settingsBackButton;
	private HSlider _settingsBgmSlider;
	private HSlider _settingsSfxSlider;
	private OptionButton _settingsWindowSizeOption;
	private OptionButton _settingsWindowModeOption;
	private HSlider _startSettingsBgmSlider;
	private HSlider _startSettingsSfxSlider;
	private OptionButton _startSettingsWindowSizeOption;
	private OptionButton _startSettingsWindowModeOption;
	private OptionButton _startSettingsLanguageOption;
	private OptionButton _settingsLanguageOption;
	private UpgradeMenu _upgradeMenu;
	private Label _scoreLabel;
	private Control _playerHealthBar;
	private Control _experienceBarRoot;
	private ProgressBar _experienceBar;
	private Label _experienceLabel;
	private Label _matchCountdownLabel;
	private Label _finalScoreLabel;
	private Label _finalSurvivalLabel;
	private Label _finalFluxGainLabel;
	private Label _finalFluxWalletLabel;
	private Label _pauseBuildSummaryLabel;
	private Label _finalBuildSummaryLabel;
	private Label _restartTitleLabel;
	private Label _restartPerfectBannerLabel;
	private Label _restartHintLabel;
	private Label _startCharacterDescriptionLabel;
	private UpgradeSystem _upgradeSystem;
	private ScoreSystem _scoreSystem;
	private StabilitySystem _stabilitySystem;
	private ProgressionSystem _progressionSystem;
	private CanvasItem _background;
	private ColorRect _backgroundDimmer;
	private Sprite2D _menuBackground;
	private ColorRect _menuDimmer;
	private CanvasItem _enemiesRoot;
	private CanvasItem _projectilesRoot;
	private CanvasItem _obstaclesRoot;
	private bool _started;
	private bool _ending;
	private bool _pauseMenuOpen;
	private bool _settingsOpen;
	private bool _startSettingsOpen;
	private bool _startCardsOpen;
	private bool _startCharacterSelectOpen;
	private bool _pendingFinalBossKillClear;
	private bool _suppressSettingsSignal;
	private string _currentRunId = string.Empty;
	private CharacterDefinition _rangedCharacter;
	private CharacterDefinition _swordsmanCharacter;
	private CharacterDefinition _tankCharacter;
	private CharacterDefinition _archerCharacter;
	private CharacterDefinition _selectedCharacterDefinition;

}
