using Godot;

public partial class GameFlowUI
{
	[ExportGroup("Node Paths")]
	[Export] private NodePath PlayerPath = "../../Player";
	[Export] private NodePath CursorRingPath = "../CursorRing";
	[Export] private NodePath TitleScreenPath = "Panels/TitleScreen";
	[Export] private NodePath StartPanelPath = "Panels/StartPanel";
	[Export] private NodePath StartMainBackToTitleMaskPath = "TransitionMask";
	[Export] private NodePath StartMainPageControllerPath = "Panels/StartPanel/MainScroll";
	[Export] private NodePath StartSettingsPageControllerPath = "Panels/StartPanel/SettingsPanel";
	[Export] private NodePath StartCardsPageControllerPath = "Panels/StartPanel/CardsPanel";
	[Export] private NodePath StartControlsPageControllerPath = "Panels/StartPanel/ControlsPanel";
	[Export] private NodePath StartCharacterPageControllerPath = "Panels/StartPanel/CharacterSelectPanel";
	[Export] private NodePath StartMainVBoxPath = "Panels/StartPanel/MainScroll/VBox";
	[Export] private NodePath StartSettingsPanelPath = "Panels/StartPanel/SettingsPanel";
	[Export] private NodePath StartSettingsTopLetterboxPath = "Panels/StartPanel/SettingsTopLetterbox";
	[Export] private NodePath StartSettingsBottomLetterboxPath = "Panels/StartPanel/SettingsBottomLetterbox";
	[Export] private NodePath StartCardsPanelPath = "Panels/StartPanel/CardsPanel";
	[Export] private NodePath StartControlsPanelPath = "Panels/StartPanel/ControlsPanel";
	[Export] private NodePath StartCharacterSelectPanelPath = "Panels/StartPanel/CharacterSelectPanel";
	[Export] private NodePath StartEventLoadoutPanelPath = "Panels/StartPanel/EventLoadoutPanel";
	[Export] private NodePath StartEventLoadoutSlotsPath = "Panels/StartPanel/EventLoadoutPanel/VBox/Slots";
	[Export] private NodePath StartEventLoadoutInventoryLabelPath = "Panels/StartPanel/EventLoadoutPanel/VBox/InventoryLabel";
	[Export] private NodePath StartEventLoadoutSummaryLabelPath = "Panels/StartPanel/EventLoadoutPanel/VBox/SummaryPanel/Margin/SummaryLabel";
	[Export] private NodePath StartEventLoadoutBackButtonPath = "Panels/StartPanel/EventLoadoutPanel/VBox/ActionButtons/BackButton";
	[Export] private NodePath StartEventLoadoutRollAllButtonPath = "Panels/StartPanel/EventLoadoutPanel/VBox/ActionButtons/RollAllButton";
	[Export] private NodePath StartEventLoadoutStartRunButtonPath = "Panels/StartPanel/EventLoadoutPanel/VBox/ActionButtons/StartRunButton";
	[Export] private NodePath StartCharacterRangedButtonPath = "Panels/StartPanel/CharacterSelectPanel/VBox/ContentRow/LeftColumn/CharacterButtons/RangedButton";
	[Export] private NodePath StartCharacterSwordsmanButtonPath = "Panels/StartPanel/CharacterSelectPanel/VBox/ContentRow/LeftColumn/CharacterButtons/SwordsmanButton";
	[Export] private NodePath StartCharacterTankButtonPath = "Panels/StartPanel/CharacterSelectPanel/VBox/ContentRow/LeftColumn/CharacterButtons/TankButton";
	[Export] private NodePath StartCharacterArcherButtonPath = "Panels/StartPanel/CharacterSelectPanel/VBox/ContentRow/LeftColumn/CharacterButtons/ArcherButton";
	[Export] private NodePath StartCharacterDescriptionPath = "Panels/StartPanel/CharacterSelectPanel/VBox/BottomRow/DetailPanel/Margin/DescScroll/SelectedCharacterDesc";
	[Export] private NodePath StartCharacterFluxValuePath = "Panels/StartPanel/CharacterSelectPanel/VBox/HeaderRow/FluxHeader/FluxValue";
	[Export] private NodePath StartCharacterBackButtonPath = "Panels/StartPanel/CharacterSelectPanel/VBox/ActionButtons/BackButton";
	[Export] private NodePath StartCharacterConfirmButtonPath = "Panels/StartPanel/CharacterSelectPanel/VBox/ActionButtons/ConfirmButton";
	[Export] private NodePath RestartPanelPath = "Panels/RestartPanel";
	[Export] private NodePath PausePanelPath = "Panels/PausePanel";
	[Export] private NodePath PauseMainVBoxPath = "Panels/PausePanel/Panel/VBox";
	[Export] private NodePath PauseSettingsPanelPath = "Panels/PausePanel/Panel/SettingsPanel";
	[Export] private NodePath StartButtonPath = "Panels/StartPanel/MainScroll/VBox/MainBody/RightColumnPanel/Margin/ButtonsVBox/StartButton";
	[Export] private NodePath StartSettingsButtonPath = "Panels/StartPanel/MainScroll/VBox/MainBody/RightColumnPanel/Margin/ButtonsVBox/SettingsButton";
	[Export] private NodePath StartCardsButtonPath = "Panels/StartPanel/MainScroll/VBox/MainBody/RightColumnPanel/Margin/ButtonsVBox/CardsButton";
	[Export] private NodePath StartLeaderboardButtonPath = "Panels/StartPanel/MainScroll/VBox/MainBody/RightColumnPanel/Margin/ButtonsVBox/LeaderboardButton";
	[Export] private NodePath StartQuitButtonPath = "Panels/StartPanel/MainScroll/VBox/MainBody/RightColumnPanel/Margin/ButtonsVBox/QuitButton";
	[Export] private NodePath StartDeleteSaveButtonPath = "Panels/StartPanel/SettingsPanel/SettingsScroll/VBox/ActionButtons/DeleteSaveButton";
	[Export] private NodePath StartDeleteSaveDialogPath = "Panels/StartPanel/DeleteSaveConfirmDialog";
	[Export] private NodePath StartPerfectLeaderboardPath = "Panels/StartPanel/MainScroll/VBox/MainBody/LeftColumn/PerfectLeaderboard";
	[Export] private NodePath StartSettingsBackButtonPath = "Panels/StartPanel/SettingsPanel/SettingsScroll/VBox/BackButton";
	[Export] private NodePath StartCardsBackButtonPath = "Panels/StartPanel/CardsPanel/VBox/BackButton";
	[Export] private NodePath StartCardsContentPath = "Panels/StartPanel/CardsPanel/VBox/CardsScroll/CardsContent";
	[Export] private NodePath StartSettingsBgmSliderPath = "Panels/StartPanel/SettingsPanel/SettingsScroll/VBox/Rows/BgmSlider";
	[Export] private NodePath StartSettingsSfxSliderPath = "Panels/StartPanel/SettingsPanel/SettingsScroll/VBox/Rows/SfxSlider";
	[Export] private NodePath StartSettingsWindowSizePath = "Panels/StartPanel/SettingsPanel/SettingsScroll/VBox/Rows/WindowSizeChoices/WindowSizeOption";
	[Export] private NodePath StartSettingsWindowModePath = "Panels/StartPanel/SettingsPanel/SettingsScroll/VBox/Rows/WindowModeChoices/WindowModeOption";
	[Export] private NodePath StartSettingsLanguagePath = "Panels/StartPanel/SettingsPanel/SettingsScroll/VBox/Rows/LanguageChoices/LanguageOption";
	[Export] private NodePath StartSettingsControlsButtonPath = "Panels/StartPanel/SettingsPanel/SettingsScroll/VBox/ActionButtons/ControlsButton";
	[Export] private NodePath StartControlsBackButtonPath = "Panels/StartPanel/ControlsPanel/VBox/ActionButtons/BackButton";
	[Export] private NodePath RestartBackToMetaButtonPath = "Panels/RestartPanel/Panel/Margin/VBox/ActionButtons/BackToMetaButton";
	[Export] private NodePath RestartButtonPath = "Panels/RestartPanel/Panel/Margin/VBox/ActionButtons/RestartButton";
	[Export] private NodePath PauseResumeButtonPath = "Panels/PausePanel/Panel/VBox/ResumeButton";
	[Export] private NodePath PauseSettingsButtonPath = "Panels/PausePanel/Panel/VBox/SettingsButton";
	[Export] private NodePath PauseRestartButtonPath = "Panels/PausePanel/Panel/VBox/RestartButton";
	[Export] private NodePath PauseToTitleButtonPath = "Panels/PausePanel/Panel/VBox/ToTitleButton";
	[Export] private NodePath PauseQuitButtonPath = "Panels/PausePanel/Panel/VBox/QuitButton";
	[Export] private NodePath SettingsBackButtonPath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/BackButton";
	[Export] private NodePath SettingsBgmSliderPath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/BgmSlider";
	[Export] private NodePath SettingsSfxSliderPath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/SfxSlider";
	[Export] private NodePath SettingsWindowSizePath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/WindowSizeOption";
	[Export] private NodePath SettingsWindowModePath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/WindowModeOption";
	[Export] private NodePath SettingsLanguagePath = "Panels/PausePanel/Panel/SettingsPanel/SettingsScroll/VBox/LanguageOption";
	[Export] private NodePath UpgradeMenuPath = "UpgradeLayer/UpgradeMenu";
	[Export] private NodePath ScoreLabelPath = "Overlay/HudOverlay/ScoreLabel";
	[Export] private NodePath PlayerHealthBarPath = "Overlay/HudOverlay/PlayerHealthBarDemo";
	[Export] private NodePath ExperienceBarRootPath = "Overlay/HudOverlay/ExperienceBarRoot";
	[Export] private NodePath ExperienceBarPath = "Overlay/HudOverlay/ExperienceBarRoot/ExperienceBar";
	[Export] private NodePath ExperienceLabelPath = "Overlay/HudOverlay/ExperienceBarRoot/ExperienceLabel";
	[Export] private NodePath MatchCountdownLabelPath = "Overlay/HudOverlay/MatchCountdownLabel";
	[Export] private NodePath EventBannerLabelPath = "Overlay/HudOverlay/EventBannerLabel";
	[Export] private NodePath EventHintLabelPath = "Overlay/HudOverlay/EventHintLabel";
	[Export] private NodePath HybridToastLabelPath = "Overlay/HudOverlay/HybridToastLabel";
	[Export] private NodePath FinalScoreLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/StatsPanel/StatsMargin/StatsVBox/StatsRow/Score";
	[Export] private NodePath FinalSurvivalLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/StatsPanel/StatsMargin/StatsVBox/StatsRow/Survival";
	[Export] private NodePath FinalFluxGainLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/StatsPanel/StatsMargin/StatsVBox/StatsRow/FluxGain";
	[Export] private NodePath FinalFluxWalletLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/StatsPanel/StatsMargin/StatsVBox/StatsRow/FluxWallet";
	[Export] private NodePath FinalShardBreakdownLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/StatsPanel/StatsMargin/StatsVBox/ShardBreakdown";
	[Export] private NodePath PauseBuildSummaryLabelPath = "Panels/PausePanel/Panel/VBox/BuildSummary";
	[Export] private NodePath FinalBuildSummaryLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/BuildSection/BuildMargin/BuildVBox/BuildScroll/BuildSummary";
	[Export] private NodePath RestartTitleLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/Header/Title";
	[Export] private NodePath RestartPerfectBannerPath = "Panels/RestartPanel/Panel/Margin/VBox/Header/PerfectBanner";
	[Export] private NodePath RestartHintLabelPath = "Panels/RestartPanel/Panel/Margin/VBox/Header/Hint";
	[Export] private NodePath BackgroundPath = "../../World/Background";
	[Export] private NodePath BackgroundDimmerPath = "../../World/BackgroundDimmer";
	[Export] private NodePath MenuBackgroundPath = "../../World/MenuBackground";
	[Export] private NodePath MenuDimmerPath = "../../World/MenuDimmer";
	[Export] private NodePath EnemiesPath = "../../Enemies";
	[Export] private NodePath ProjectilesPath = "../../Projectiles";
	[Export] private NodePath ObstaclesPath = "../../World/Obstacles";
	private const string RangedCharacterResourcePath = "res://Data/Characters/RangedCharacter.tres";
	private const string SwordsmanCharacterResourcePath = "res://Data/Characters/SwordsmanCharacter.tres";
	private const string TankCharacterResourcePath = "res://Data/Characters/TankBurstCharacter.tres";
	private const string ArcherCharacterResourcePath = "res://Data/Characters/ArcherCharacter.tres";

	private Player _player;
	private CursorRing _cursorRing;
	private PlayerHealth _playerHealth;
	private Control _titleScreenPanel;
	private Control _startPanel;
	private ColorRect _startMainBackToTitleMask;
	private StartMainPageController _startMainPageController;
	private StartSettingsPageController _startSettingsPageController;
	private StartCardsPageController _startCardsPageController;
	private StartControlsPageController _startControlsPageController;
	private StartCharacterSelectPageController _startCharacterPageController;
	private Control _startMainVBox;
	private Control _startSettingsPanel;
	private ColorRect _startSettingsTopLetterbox;
	private ColorRect _startSettingsBottomLetterbox;
	private Control _startCardsPanel;
	private Control _startControlsPanel;
	private Control _startCharacterSelectPanel;
	private Control _startEventLoadoutPanel;
	private Control _restartPanel;
	private Control _pausePanel;
	private Control _pauseMainVBox;
	private Control _pauseSettingsPanel;
	private Button _startButton;
	private Button _startSettingsButton;
	private Button _startCardsButton;
	private Button _startLeaderboardButton;
	private Button _startQuitButton;
	private Button _startDeleteSaveButton;
	private Button _startSettingsControlsButton;
	private ConfirmationDialog _startDeleteSaveDialog;
	private Label _startPerfectLeaderboardLabel;
	private Button _startSettingsBackButton;
	private Button _startCardsBackButton;
	private Button _startControlsBackButton;
	private Label _startCardsContentLabel;
	private Button _startCharacterRangedButton;
	private Button _startCharacterSwordsmanButton;
	private Button _startCharacterTankButton;
	private Button _startCharacterArcherButton;
	private Label _startCharacterFluxValueLabel;
	private Button _startCharacterBackButton;
	private Button _startCharacterConfirmButton;
	private Button _startEventLoadoutBackButton;
	private Button _startEventLoadoutRollAllButton;
	private Button _startEventLoadoutStartRunButton;
	private Label _startEventLoadoutInventoryLabel;
	private Label _startEventLoadoutSummaryLabel;
	private Button _restartBackToMetaButton;
	private Button _restartButton;
	private Button _pauseResumeButton;
	private Button _pauseSettingsButton;
	private Button _pauseRestartButton;
	private Button _pauseToTitleButton;
	private Button _pauseQuitButton;
	private Button _settingsBackButton;
	private HSlider _settingsBgmSlider;
	private HSlider _settingsSfxSlider;
	private OptionButton _settingsWindowSizeOption;
	private OptionButton _settingsWindowModeOption;
	private HSlider _startSettingsBgmSlider;
	private HSlider _startSettingsSfxSlider;
	private OptionButton _startSettingsWindowSizeOption;
	private OptionButton _startSettingsWindowModeOption;
	private OptionButton _startSettingsLanguageOption;
	private OptionButton _settingsLanguageOption;
	private UpgradeMenu _upgradeMenu;
	private Label _scoreLabel;
	private Control _playerHealthBar;
	private Control _experienceBarRoot;
	private ProgressBar _experienceBar;
	private Label _experienceLabel;
	private Label _matchCountdownLabel;
	private Label _eventBannerLabel;
	private Label _eventHintLabel;
	private Label _hybridToastLabel;
	private Label _finalScoreLabel;
	private Label _finalSurvivalLabel;
	private Label _finalFluxGainLabel;
	private Label _finalFluxWalletLabel;
	private Label _finalShardBreakdownLabel;
	private Label _pauseBuildSummaryLabel;
	private Label _finalBuildSummaryLabel;
	private Label _restartTitleLabel;
	private Label _restartPerfectBannerLabel;
	private Label _restartHintLabel;
	private Label _startCharacterDescriptionLabel;
	private UpgradeSystem _upgradeSystem;
	private ScoreSystem _scoreSystem;
	private StabilitySystem _stabilitySystem;
	private ProgressionSystem _progressionSystem;
	private EventDirector _eventDirector;
	private CanvasItem _background;
	private ColorRect _backgroundDimmer;
	private Sprite2D _menuBackground;
	private ColorRect _menuDimmer;
	private CanvasItem _enemiesRoot;
	private CanvasItem _projectilesRoot;
	private CanvasItem _obstaclesRoot;
	private Tween _startMainBackToTitleMaskTween;
	private bool _started;
	private bool _ending;
	private bool _bootTitleScreenOpen;
	private bool _pauseMenuOpen;
	private bool _settingsOpen;
	private bool _startSettingsOpen;
	private bool _startCardsOpen;
	private bool _startControlsOpen;
	private bool _startCharacterSelectOpen;
	private bool _startEventLoadoutOpen;
	private bool _startMainBackToTitleTransitionActive;
	private bool _pendingFinalBossKillClear;
	private bool _suppressSettingsSignal;
	private string _currentRunId = string.Empty;
	private CharacterDefinition _rangedCharacter;
	private CharacterDefinition _swordsmanCharacter;
	private CharacterDefinition _tankCharacter;
	private CharacterDefinition _archerCharacter;
	private CharacterDefinition _selectedCharacterDefinition;
	private readonly GameFlowUiSharedState _sharedState = new();
	private readonly OptionButton[] _startEventLoadoutDomainOptions = new OptionButton[4];
	private readonly Button[] _startEventLoadoutRollButtons = new Button[4];
	private readonly Label[] _startEventLoadoutResultLabels = new Label[4];
	private readonly EventLoadoutDraftSlot[] _eventLoadoutDraftSlots = new EventLoadoutDraftSlot[4];

}
