public enum UpgradeId
{
	PrimaryDamageUp,
	PrimaryFasterFire,
	PrimaryProjectileSpeedUp,
	SecondaryDamageUp,
	SecondaryRangeUp,
	SecondaryWiderArc,
	PressureKillProgressUp,
	PressureThresholdDown,
	PressureTriggerReliefUp,
	PressureTimeProgressUp,
	StabilityDecayDown,
	StabilityRecoveryPulse,
	AnomalyLongerEvents,
	AnomalyPowerResonance,
	DashFasterCooldown,
	DashSpeedUp,
	DashLonger,
	DashIFrameUp,
	MaxHpUp,
	RiskVolatileArms
}
